
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.caerulaarbor.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.caerulaarbor.CaerulaArborMod;

public class CaerulaArborModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CaerulaArborMod.MODID);
	public static final RegistryObject<CreativeModeTab> CAERULA_ITEMS = REGISTRY.register("caerula_items",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.caerula_items")).icon(() -> new ItemStack(CaerulaArborModItems.CAERULA_RECORDER.get())).displayItems((parameters, tabData) -> {
				tabData.accept(CaerulaArborModItems.CAERULA_RECORDER.get());
				tabData.accept(CaerulaArborModItems.THERMOGRAPH.get());
				tabData.accept(CaerulaArborModItems.TRAILED_WOODEN_SWORD.get());
				tabData.accept(CaerulaArborModItems.TRAILED_STONE_SWORD.get());
				tabData.accept(CaerulaArborModItems.TRAILED_IRON_SWORD.get());
				tabData.accept(CaerulaArborModItems.TRAILED_DIAMOND_SWORD.get());
				tabData.accept(CaerulaArborModItems.TRAILED_NETHERITE_SWORD.get());
				tabData.accept(CaerulaArborModItems.TRAILED_GOLDEN_SWORD.get());
				tabData.accept(CaerulaArborModItems.SWORD_OCEAN_CRYSTAL.get());
				tabData.accept(CaerulaArborModItems.PICKAXE_OCEAN_CRYSTAL.get());
				tabData.accept(CaerulaArborModItems.AXE_OCEAN_CRYSTAL.get());
				tabData.accept(CaerulaArborModItems.SHOVEL_OCEAN_CRYSTAL.get());
				tabData.accept(CaerulaArborModItems.HOE_OCEAN_CRYSTAL.get());
				tabData.accept(CaerulaArborModItems.CHITIN_SWORD.get());
				tabData.accept(CaerulaArborModItems.CHITIN_PICKAXE.get());
				tabData.accept(CaerulaArborModItems.CHITIN_AXE.get());
				tabData.accept(CaerulaArborModItems.CHITIN_SHOVEL.get());
				tabData.accept(CaerulaArborModItems.CHITIN_HOE.get());
				tabData.accept(CaerulaArborModItems.COMPLEX_CHITIN_SWORD.get());
				tabData.accept(CaerulaArborModItems.COMPLEX_CHITIN_PICKAXE.get());
				tabData.accept(CaerulaArborModItems.COMPLEX_CHITIN_AXE.get());
				tabData.accept(CaerulaArborModItems.COMPLEX_CHITIN_SHOVEL.get());
				tabData.accept(CaerulaArborModItems.COMPLEX_CHITIN_HOE.get());
				tabData.accept(CaerulaArborModItems.LEGENDARY_SPEAR.get());
				tabData.accept(CaerulaArborModItems.PHLOEM_BOW.get());
				tabData.accept(CaerulaArborModItems.THE_SPEAR.get());
				tabData.accept(CaerulaArborModItems.MUSIC_BOX_FIXED.get());
				tabData.accept(CaerulaArborModItems.FLUORE_BERRIES.get());
				tabData.accept(CaerulaArborModItems.RADIANT_BERRIES.get());
				tabData.accept(CaerulaArborModBlocks.TRAIL_CAKE.get().asItem());
				tabData.accept(CaerulaArborModItems.TRAIL_CAKE_PIECE.get());
				tabData.accept(CaerulaArborModBlocks.CARAMEL_CAKE.get().asItem());
				tabData.accept(CaerulaArborModItems.CARAMEL_CAKE_PIECE.get());
				tabData.accept(CaerulaArborModBlocks.REDSTONE_IRIS.get().asItem());
				tabData.accept(CaerulaArborModBlocks.REDSTONEIRIS_SEEDING.get().asItem());
				tabData.accept(CaerulaArborModBlocks.SEA_TRAIL_INIT.get().asItem());
				tabData.accept(CaerulaArborModBlocks.SEA_TRAIL_GROWING.get().asItem());
				tabData.accept(CaerulaArborModBlocks.SEA_TRAIL_GROWN.get().asItem());
				tabData.accept(CaerulaArborModItems.WEARABLE_CROWN_HELMET.get());
				tabData.accept(CaerulaArborModItems.WEARABLE_CHEST_CHESTPLATE.get());
				tabData.accept(CaerulaArborModItems.CHITIN_ARMOR_HELMET.get());
				tabData.accept(CaerulaArborModItems.CHITIN_ARMOR_CHESTPLATE.get());
				tabData.accept(CaerulaArborModItems.CHITIN_ARMOR_LEGGINGS.get());
				tabData.accept(CaerulaArborModItems.CHITIN_ARMOR_BOOTS.get());
				tabData.accept(CaerulaArborModItems.COMPLEXCHITIN_ARMOR_HELMET.get());
				tabData.accept(CaerulaArborModItems.COMPLEXCHITIN_ARMOR_CHESTPLATE.get());
				tabData.accept(CaerulaArborModItems.COMPLEXCHITIN_ARMOR_LEGGINGS.get());
				tabData.accept(CaerulaArborModItems.COMPLEXCHITIN_ARMOR_BOOTS.get());
				tabData.accept(CaerulaArborModBlocks.KINGS_ARMOR.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BLOCK_CROWN.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BLOCK_SPEAR.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BLOCK_EXTENSION.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BLOCK_CRYSTAL.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BLOCK_FATE.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BERRY_CAN.get().asItem());
				tabData.accept(CaerulaArborModBlocks.TIDE_OBSERVATION.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BOMB_TRAILER.get().asItem());
				tabData.accept(CaerulaArborModBlocks.ANCHOR_LOWER.get().asItem());
				tabData.accept(CaerulaArborModBlocks.ANCHOR_MEDIUM.get().asItem());
				tabData.accept(CaerulaArborModBlocks.ANCHOR_UPPER.get().asItem());
				tabData.accept(CaerulaArborModBlocks.CHITIN_BLOCK.get().asItem());
				tabData.accept(CaerulaArborModBlocks.OCEAN_CRYSTAL_BLOCK.get().asItem());
				tabData.accept(CaerulaArborModBlocks.COMPLEX_CHITIN_BLOCK.get().asItem());
				tabData.accept(CaerulaArborModBlocks.OCEAN_GLASS.get().asItem());
				tabData.accept(CaerulaArborModBlocks.OCEAN_GLASSPANE.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BLOCK_KETTLE.get().asItem());
				tabData.accept(CaerulaArborModBlocks.ALLAY_BLOCK.get().asItem());
				tabData.accept(CaerulaArborModBlocks.BLOCK_BATBED.get().asItem());
				tabData.accept(CaerulaArborModItems.REDSTONE_INGOT.get());
				tabData.accept(CaerulaArborModItems.OCEAN_EYE.get());
				tabData.accept(CaerulaArborModItems.FERMENTED_OCEAN_EYE.get());
				tabData.accept(CaerulaArborModItems.OCEAN_MACHINE.get());
				tabData.accept(CaerulaArborModItems.OCEAN_TRIM_TEMPLATE.get());
				tabData.accept(CaerulaArborModItems.COMPLEX_CHITIN.get());
				tabData.accept(CaerulaArborModItems.EMPTY_CAN.get());
				tabData.accept(CaerulaArborModItems.CANNED_WATER.get());
				tabData.accept(CaerulaArborModItems.CANNED_LAVA.get());
				tabData.accept(CaerulaArborModItems.CANNED_BOILED_WATER.get());
				tabData.accept(CaerulaArborModItems.PAPER_BAG.get());
				tabData.accept(CaerulaArborModItems.CAFFEINE.get());
				tabData.accept(CaerulaArborModItems.SEA_TRAIL_MOR.get());
				tabData.accept(CaerulaArborModItems.COOKED_MOR.get());
				tabData.accept(CaerulaArborModItems.CARAMEL_MOR.get());
				tabData.accept(CaerulaArborModItems.BONE_SHARD.get());
				tabData.accept(CaerulaArborModItems.OCEAN_PHLOEM.get());
				tabData.accept(CaerulaArborModItems.OCEAN_FIBRE.get());
				tabData.accept(CaerulaArborModItems.COOKED_FIBRE.get());
				tabData.accept(CaerulaArborModItems.OCEAN_CRYSTAL.get());
				tabData.accept(CaerulaArborModItems.OCEAN_CUTIN.get());
				tabData.accept(CaerulaArborModItems.CUTIN_STICK.get());
				tabData.accept(CaerulaArborModItems.OCEAN_CHITIN.get());
				tabData.accept(CaerulaArborModItems.INSTANT_NOODLE.get());
				tabData.accept(CaerulaArborModItems.OBISIDIAN_BALL.get());
				tabData.accept(CaerulaArborModItems.FAKE_EGG.get());
				tabData.accept(CaerulaArborModItems.REAL_EGG.get());
				tabData.accept(CaerulaArborModItems.TRAIL_CREAM.get());
			}).build());
	public static final RegistryObject<CreativeModeTab> CAECULA_RELICS = REGISTRY.register("caecula_relics",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.caecula_relics")).icon(() -> new ItemStack(CaerulaArborModItems.RELIC_CURSE_EMELIGHT.get())).displayItems((parameters, tabData) -> {
				tabData.accept(CaerulaArborModItems.RELIC_CURSE_EMELIGHT.get());
				tabData.accept(CaerulaArborModItems.RELIC_CURSED_GLOWBODY.get());
				tabData.accept(CaerulaArborModItems.RELIC_CURSED_RESEARCH.get());
				tabData.accept(CaerulaArborModItems.RELIC_CROWN.get());
				tabData.accept(CaerulaArborModItems.KINGS_ARMOUR.get());
				tabData.accept(CaerulaArborModItems.KINGS_SPEAR.get());
				tabData.accept(CaerulaArborModItems.KINGS_EXTENSION.get());
				tabData.accept(CaerulaArborModItems.KINGS_CRYSTAL.get());
				tabData.accept(CaerulaArborModItems.ARCHFIENDS_ARTIFACT.get());
				tabData.accept(CaerulaArborModItems.ARCHFIENDS_FLAG.get());
				tabData.accept(CaerulaArborModItems.ARCHFIENDS_BED.get());
				tabData.accept(CaerulaArborModItems.ROYAL_FATE.get());
				tabData.accept(CaerulaArborModItems.SURVIVOR_CONTRACT.get());
				tabData.accept(CaerulaArborModItems.CRIMSON_TREATY.get());
				tabData.accept(CaerulaArborModItems.CHITIN_KNIFE.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_THORNS.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_STRANGLE.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_FERTILIY.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_SPEED.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_BARREN.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_SPOTLESS.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_FIREWORK.get());
				tabData.accept(CaerulaArborModItems.HAND_OF_ENGRAVE.get());
				tabData.accept(CaerulaArborModItems.HAND_SWORD.get());
				tabData.accept(CaerulaArborModItems.MEAT_CAN.get());
				tabData.accept(CaerulaArborModItems.BOWL_SEAGRASS.get());
				tabData.accept(CaerulaArborModItems.GOLDEN_STORM.get());
				tabData.accept(CaerulaArborModItems.CANNED_CHERRY.get());
				tabData.accept(CaerulaArborModItems.AROMATIC_COFFEE.get());
				tabData.accept(CaerulaArborModItems.COFFEE_CANDY.get());
				tabData.accept(CaerulaArborModItems.RAINBOW_CANDY.get());
				tabData.accept(CaerulaArborModItems.SOLO_MUSIC_BOX.get());
				tabData.accept(CaerulaArborModItems.ODD_FLUTE.get());
				tabData.accept(CaerulaArborModItems.REDSTONE_IRIS_FLOWER.get());
				tabData.accept(CaerulaArborModItems.RESCISSION.get());
				tabData.accept(CaerulaArborModItems.SCORE.get());
				tabData.accept(CaerulaArborModItems.OMNI_KEY.get());
				tabData.accept(CaerulaArborModItems.GUARDIAN_STARE.get());
				tabData.accept(CaerulaArborModItems.VOYAGE_OF_GOLD.get());
				tabData.accept(CaerulaArborModItems.PIGLIN_DIARY.get());
				tabData.accept(CaerulaArborModItems.TOPONYM_TEXTOLOGY.get());
				tabData.accept(CaerulaArborModItems.KETTLE.get());
				tabData.accept(CaerulaArborModItems.ALLAY_SCULPTURE.get());
				tabData.accept(CaerulaArborModItems.BAT_BED.get());
				tabData.accept(CaerulaArborModItems.PROOF_OF_LONGEVITY.get());
			}).withTabsBefore(CAERULA_ITEMS.getId()).build());
	public static final RegistryObject<CreativeModeTab> CAERULA_LIVINGS = REGISTRY.register("caerula_livings",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.caerula_arbor.caerula_livings")).icon(() -> new ItemStack(CaerulaArborModItems.RELIC_CURSED_GLOWBODY.get())).displayItems((parameters, tabData) -> {
				tabData.accept(CaerulaArborModItems.RUN_FISH_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.SLIDER_FISH_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.SHOOTER_FISH_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.FLY_FISH_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.REAPER_FISH_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.CREEPER_FISH_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.PUNCTURE_FISH_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.BASELAYER_ABYSSAL_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.PREDATOR_ABYSSAL_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.GUIDE_ABYSSAL_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.SPLASHER_ABYSSAL_SPAWN_EGG.get());
				tabData.accept(CaerulaArborModItems.UMBRELLA_ABYSSAL_SPAWN_EGG.get());
			}).withTabsBefore(CAECULA_RELICS.getId()).build());
}
