package com.apocalypse.caerulaarbor.init;

import com.apocalypse.caerulaarbor.CaerulaArborMod;
import com.apocalypse.caerulaarbor.item.relic.normal.HotWaterKettleItem;
import com.apocalypse.caerulaarbor.procedures.GetMusicboxPlayerProcedure;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import com.apocalypse.caerulaarbor.item.WearableCrownItem;
import com.apocalypse.caerulaarbor.item.WearableChestItem;
import com.apocalypse.caerulaarbor.item.relic.epic.PureGoldExpeditionItem;
import com.apocalypse.caerulaarbor.item.TransformCellItem;
import com.apocalypse.caerulaarbor.item.TrailedWoodenSwordItem;
import com.apocalypse.caerulaarbor.item.TrailedStoneSwordItem;
import com.apocalypse.caerulaarbor.item.TrailedNetheriteSwordItem;
import com.apocalypse.caerulaarbor.item.TrailedIronSwordItem;
import com.apocalypse.caerulaarbor.item.TrailedGoldenSwordItem;
import com.apocalypse.caerulaarbor.item.TrailedDiamondSwordItem;
import com.apocalypse.caerulaarbor.item.TrailCreamItem;
import com.apocalypse.caerulaarbor.item.TrailCakePieceItem;
import com.apocalypse.caerulaarbor.item.ToponymTextologyItem;
import com.apocalypse.caerulaarbor.item.ThermographItem;
import com.apocalypse.caerulaarbor.item.TheSpearItem;
import com.apocalypse.caerulaarbor.item.SwordOceanCrystalItem;
import com.apocalypse.caerulaarbor.item.relic.epic.SurvivorContractItem;
import com.apocalypse.caerulaarbor.item.SoloMusicBoxItem;
import com.apocalypse.caerulaarbor.item.SeaTrailMorItem;
import com.apocalypse.caerulaarbor.item.ScoreItem;
import com.apocalypse.caerulaarbor.item.SampleSubsistingItem;
import com.apocalypse.caerulaarbor.item.SampleMigrationItem;
import com.apocalypse.caerulaarbor.item.SampleGrowItem;
import com.apocalypse.caerulaarbor.item.SampleBreedItem;
import com.apocalypse.caerulaarbor.item.RoyalFateItem;
import com.apocalypse.caerulaarbor.item.RescissionItem;
import com.apocalypse.caerulaarbor.item.RelicCursedRESEARCHItem;
import com.apocalypse.caerulaarbor.item.RelicCursedGLOWBODYItem;
import com.apocalypse.caerulaarbor.item.RelicCurseEMELIGHTItem;
import com.apocalypse.caerulaarbor.item.RelicCROWNItem;
import com.apocalypse.caerulaarbor.item.RedstoneIrisFlowerItem;
import com.apocalypse.caerulaarbor.item.RedstoneIngotItem;
import com.apocalypse.caerulaarbor.item.RealEggItem;
import com.apocalypse.caerulaarbor.item.relic.epic.PittsAssortedFruitsItem;
import com.apocalypse.caerulaarbor.item.RadiantBerriesItem;
import com.apocalypse.caerulaarbor.item.relic.epic.ProofOfLongevityItem;
import com.apocalypse.caerulaarbor.item.DurinOvergroundOdysseyItem;
import com.apocalypse.caerulaarbor.item.PhloemBowItem;
import com.apocalypse.caerulaarbor.item.PaperBagItem;
import com.apocalypse.caerulaarbor.item.OmniKeyItem;
import com.apocalypse.caerulaarbor.item.relic.rare.WeirdFluteItem;
import com.apocalypse.caerulaarbor.item.OceanthornShovelItem;
import com.apocalypse.caerulaarbor.item.OceanthornPickaxeItem;
import com.apocalypse.caerulaarbor.item.OceanthornHoeItem;
import com.apocalypse.caerulaarbor.item.OceanthornAxeItem;
import com.apocalypse.caerulaarbor.item.OceanTrimTemplateItem;
import com.apocalypse.caerulaarbor.item.OceanPhloemItem;
import com.apocalypse.caerulaarbor.item.OceanPeduncleItem;
import com.apocalypse.caerulaarbor.item.OceanMachineItem;
import com.apocalypse.caerulaarbor.item.OceanFibreItem;
import com.apocalypse.caerulaarbor.item.OceanEyeItem;
import com.apocalypse.caerulaarbor.item.OceanCutinItem;
import com.apocalypse.caerulaarbor.item.OceanCrystalItem;
import com.apocalypse.caerulaarbor.item.OceanChitinItem;
import com.apocalypse.caerulaarbor.item.OceanCellItem;
import com.apocalypse.caerulaarbor.item.OceanArrowItem;
import com.apocalypse.caerulaarbor.item.ObisidianBallItem;
import com.apocalypse.caerulaarbor.item.MusicBoxFixedItem;
import com.apocalypse.caerulaarbor.item.relic.normal.FeaturedCannedMeatItem;
import com.apocalypse.caerulaarbor.item.LegendarySpearItem;
import com.apocalypse.caerulaarbor.item.LanguageKeyItem;
import com.apocalypse.caerulaarbor.item.KingsSpearItem;
import com.apocalypse.caerulaarbor.item.KingsExtensionItem;
import com.apocalypse.caerulaarbor.item.KingsCrystalItem;
import com.apocalypse.caerulaarbor.item.KingsArmourItem;
import com.apocalypse.caerulaarbor.item.InstantNoodleItem;
import com.apocalypse.caerulaarbor.item.HandSwordItem;
import com.apocalypse.caerulaarbor.item.HandOfThornsItem;
import com.apocalypse.caerulaarbor.item.HandOfSwipeItem;
import com.apocalypse.caerulaarbor.item.HandOfStrangleItem;
import com.apocalypse.caerulaarbor.item.HandOfSpeedItem;
import com.apocalypse.caerulaarbor.item.HandOfFireworkItem;
import com.apocalypse.caerulaarbor.item.HandOfFertiliyItem;
import com.apocalypse.caerulaarbor.item.HandOfEngraveItem;
import com.apocalypse.caerulaarbor.item.HandOfBarrenItem;
import com.apocalypse.caerulaarbor.item.GuardianStareItem;
import com.apocalypse.caerulaarbor.item.GoldenStormItem;
import com.apocalypse.caerulaarbor.item.FluoreBerriesItem;
import com.apocalypse.caerulaarbor.item.FermentedOceanEyeItem;
import com.apocalypse.caerulaarbor.item.FakeEggItem;
import com.apocalypse.caerulaarbor.item.EmptyCanItem;
import com.apocalypse.caerulaarbor.item.ElitePeduncleItem;
import com.apocalypse.caerulaarbor.item.DispatchStickItem;
import com.apocalypse.caerulaarbor.item.CutinStickItem;
import com.apocalypse.caerulaarbor.item.CrimsonTreatyItem;
import com.apocalypse.caerulaarbor.item.CookedPeduncleItem;
import com.apocalypse.caerulaarbor.item.CookedMorItem;
import com.apocalypse.caerulaarbor.item.CookedFibreItem;
import com.apocalypse.caerulaarbor.item.CookedCellClusterItem;
import com.apocalypse.caerulaarbor.item.CookedBrokenCellClusterItem;
import com.apocalypse.caerulaarbor.item.ComplexchitinArmorItem;
import com.apocalypse.caerulaarbor.item.ComplexChitinSwordItem;
import com.apocalypse.caerulaarbor.item.ComplexChitinShovelItem;
import com.apocalypse.caerulaarbor.item.ComplexChitinPickaxeItem;
import com.apocalypse.caerulaarbor.item.ComplexChitinItem;
import com.apocalypse.caerulaarbor.item.ComplexChitinHoeItem;
import com.apocalypse.caerulaarbor.item.ComplexChitinAxeItem;
import com.apocalypse.caerulaarbor.item.CoinOfTradeItem;
import com.apocalypse.caerulaarbor.item.CoffeeCandyItem;
import com.apocalypse.caerulaarbor.item.ChitinSwordItem;
import com.apocalypse.caerulaarbor.item.ChitinShovelItem;
import com.apocalypse.caerulaarbor.item.ChitinPickaxeItem;
import com.apocalypse.caerulaarbor.item.ChitinKnifeItem;
import com.apocalypse.caerulaarbor.item.ChitinHoeItem;
import com.apocalypse.caerulaarbor.item.ChitinAxeItem;
import com.apocalypse.caerulaarbor.item.ChitinArmorItem;
import com.apocalypse.caerulaarbor.item.CellClusterItem;
import com.apocalypse.caerulaarbor.item.CaramelMorItem;
import com.apocalypse.caerulaarbor.item.CaramelCakePieceItem;
import com.apocalypse.caerulaarbor.item.CannedWaterItem;
import com.apocalypse.caerulaarbor.item.CannedNoodleItem;
import com.apocalypse.caerulaarbor.item.CannedLavaItem;
import com.apocalypse.caerulaarbor.item.relic.rare.ScreamingCherryItem;
import com.apocalypse.caerulaarbor.item.CannedBoiledWaterItem;
import com.apocalypse.caerulaarbor.item.CaffeineItem;
import com.apocalypse.caerulaarbor.item.CaerulaRecorderItem;
import com.apocalypse.caerulaarbor.item.CaerulaHeartItem;
import com.apocalypse.caerulaarbor.item.BrokenOceanCellItem;
import com.apocalypse.caerulaarbor.item.BrokenCellClusterItem;
import com.apocalypse.caerulaarbor.item.BowlSeagrassItem;
import com.apocalypse.caerulaarbor.item.BoneShardItem;
import com.apocalypse.caerulaarbor.item.relic.rare.VampiresBedItem;
import com.apocalypse.caerulaarbor.item.AromaticCoffeeItem;
import com.apocalypse.caerulaarbor.item.ArchfiendsFlagItem;
import com.apocalypse.caerulaarbor.item.ArchfiendsBedItem;
import com.apocalypse.caerulaarbor.item.ArchfiendsArtifactItem;
import com.apocalypse.caerulaarbor.item.AlleySculptureItem;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class ModItems {

    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, CaerulaArborMod.MODID);

    public static final RegistryObject<Item> CAERULA_RECORDER = ITEMS.register("caerula_recorder", () -> new CaerulaRecorderItem());
    public static final RegistryObject<Item> RELIC_CURSE_EMELIGHT = ITEMS.register("relic_curse_emelight", () -> new RelicCurseEMELIGHTItem());
    public static final RegistryObject<Item> EMERGENCY_LIGHT = block(ModBlocks.EMERGENCY_LIGHT);
    public static final RegistryObject<Item> RELIC_CURSED_GLOWBODY = ITEMS.register("relic_cursed_glowbody", () -> new RelicCursedGLOWBODYItem());
    public static final RegistryObject<Item> RELIC_CURSED_RESEARCH = ITEMS.register("relic_cursed_research", () -> new RelicCursedRESEARCHItem());
    public static final RegistryObject<Item> RELIC_CROWN = ITEMS.register("relic_crown", () -> new RelicCROWNItem());
    public static final RegistryObject<Item> KINGS_ARMOUR = ITEMS.register("kings_armour", () -> new KingsArmourItem());
    public static final RegistryObject<Item> KINGS_ARMOR = block(ModBlocks.KINGS_ARMOR);
    public static final RegistryObject<Item> BLOCK_CROWN = block(ModBlocks.BLOCK_CROWN);
    public static final RegistryObject<Item> KINGS_SPEAR = ITEMS.register("kings_spear", () -> new KingsSpearItem());
    public static final RegistryObject<Item> BLOCK_SPEAR = block(ModBlocks.BLOCK_SPEAR);
    public static final RegistryObject<Item> KINGS_EXTENSION = ITEMS.register("kings_extension", () -> new KingsExtensionItem());
    public static final RegistryObject<Item> BLOCK_EXTENSION = block(ModBlocks.BLOCK_EXTENSION);
    public static final RegistryObject<Item> KINGS_CRYSTAL = ITEMS.register("kings_crystal", () -> new KingsCrystalItem());
    public static final RegistryObject<Item> BLOCK_CRYSTAL = block(ModBlocks.BLOCK_CRYSTAL);
    public static final RegistryObject<Item> REDSTONE_INGOT = ITEMS.register("redstone_ingot", () -> new RedstoneIngotItem());
    public static final RegistryObject<Item> THE_SPEAR = ITEMS.register("the_spear", () -> new TheSpearItem());
    public static final RegistryObject<Item> WEARABLE_CHEST_CHESTPLATE = ITEMS.register("wearable_chest_chestplate", () -> new WearableChestItem.Chestplate());
    public static final RegistryObject<WearableCrownItem> WEARABLE_CROWN_HELMET = ITEMS.register("wearable_crown_helmet", () -> new WearableCrownItem(ArmorItem.Type.HELMET, new Item.Properties().fireResistant()));
    public static final RegistryObject<Item> HAND_OF_THORNS = ITEMS.register("hand_of_thorns", () -> new HandOfThornsItem());
    public static final RegistryObject<Item> HAND_OF_STRANGLE = ITEMS.register("hand_of_strangle", () -> new HandOfStrangleItem());
    public static final RegistryObject<Item> HAND_OF_FERTILIY = ITEMS.register("hand_of_fertiliy", () -> new HandOfFertiliyItem());
    public static final RegistryObject<Item> HAND_OF_SPEED = ITEMS.register("hand_of_speed", () -> new HandOfSpeedItem());
    public static final RegistryObject<Item> HAND_OF_BARREN = ITEMS.register("hand_of_barren", () -> new HandOfBarrenItem());
    public static final RegistryObject<Item> FLUORE_BERRIES = ITEMS.register("fluore_berries", () -> new FluoreBerriesItem());
    public static final RegistryObject<Item> RADIANT_BERRIES = ITEMS.register("radiant_berries", () -> new RadiantBerriesItem());
    public static final RegistryObject<Item> HAND_OF_SPOTLESS = ITEMS.register("hand_of_spotless", () -> new HandOfSwipeItem());
    public static final RegistryObject<Item> ARCHFIENDS_ARTIFACT = ITEMS.register("archfiends_artifact", () -> new ArchfiendsArtifactItem());
    public static final RegistryObject<Item> HAND_OF_FIREWORK = ITEMS.register("hand_of_firework", () -> new HandOfFireworkItem());
    public static final RegistryObject<Item> ARCHFIENDS_FLAG = ITEMS.register("archfiends_flag", () -> new ArchfiendsFlagItem());
    public static final RegistryObject<Item> HAND_OF_ENGRAVE = ITEMS.register("hand_of_engrave", () -> new HandOfEngraveItem());
    public static final RegistryObject<Item> ARCHFIENDS_BED = ITEMS.register("archfiends_bed", () -> new ArchfiendsBedItem());
    public static final RegistryObject<Item> ROYAL_FATE = ITEMS.register("royal_fate", () -> new RoyalFateItem());
    public static final RegistryObject<Item> BLOCK_FATE = block(ModBlocks.BLOCK_FATE);
    public static final RegistryObject<Item> CRIMSON_TREATY = ITEMS.register("crimson_treaty", () -> new CrimsonTreatyItem());
    public static final RegistryObject<Item> MEAT_CAN = ITEMS.register("meat_can", () -> new FeaturedCannedMeatItem());
    public static final RegistryObject<Item> EMPTY_CAN = ITEMS.register("empty_can", () -> new EmptyCanItem());
    public static final RegistryObject<Item> BOWL_SEAGRASS = ITEMS.register("bowl_seagrass", () -> new BowlSeagrassItem());
    public static final RegistryObject<Item> GOLDEN_STORM = ITEMS.register("golden_storm", () -> new GoldenStormItem());
    public static final RegistryObject<Item> PAPER_BAG = ITEMS.register("paper_bag", () -> new PaperBagItem());
    public static final RegistryObject<Item> COFFEE_CANDY = ITEMS.register("coffee_candy", () -> new CoffeeCandyItem());
    public static final RegistryObject<Item> CAFFEINE = ITEMS.register("caffeine", () -> new CaffeineItem());
    public static final RegistryObject<Item> AROMATIC_COFFEE = ITEMS.register("aromatic_coffee", () -> new AromaticCoffeeItem());
    public static final RegistryObject<Item> SOLO_MUSIC_BOX = ITEMS.register("solo_music_box", () -> new SoloMusicBoxItem());
    public static final RegistryObject<Item> MUSIC_BOX_FIXED = ITEMS.register("music_box_fixed", () -> new MusicBoxFixedItem());
    public static final RegistryObject<Item> REDSTONE_IRIS = block(ModBlocks.REDSTONE_IRIS);
    public static final RegistryObject<Item> REDSTONE_IRIS_FLOWER = ITEMS.register("redstone_iris_flower", () -> new RedstoneIrisFlowerItem());
    public static final RegistryObject<Item> REDSTONEIRIS_SEEDING = block(ModBlocks.REDSTONEIRIS_SEEDING);
    public static final RegistryObject<Item> THERMOGRAPH = ITEMS.register("thermograph", () -> new ThermographItem());
    public static final RegistryObject<Item> TOPONYM_TEXTOLOGY = ITEMS.register("toponym_textology", () -> new ToponymTextologyItem());
    public static final RegistryObject<Item> RUN_FISH_SPAWN_EGG = ITEMS.register("run_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.RUN_FISH, -16777012, -3355444, new Item.Properties()));
    public static final RegistryObject<Item> SLIDER_FISH_SPAWN_EGG = ITEMS.register("slider_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SLIDER_FISH, -13421569, -3355444, new Item.Properties()));
    public static final RegistryObject<Item> SUPER_SLIDER_SPAWN_EGG = ITEMS.register("super_slider_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SUPER_SLIDER, -13434778, -3355393, new Item.Properties()));
    public static final RegistryObject<Item> SHOOTER_FISH_SPAWN_EGG = ITEMS.register("shooter_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SHOOTER_FISH, -13434676, -3355444, new Item.Properties()));
    public static final RegistryObject<Item> FLY_FISH_SPAWN_EGG = ITEMS.register("fly_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FLY_FISH, -16737895, -3355444, new Item.Properties()));
    public static final RegistryObject<Item> REAPER_FISH_SPAWN_EGG = ITEMS.register("reaper_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.REAPER_FISH, -6710785, -3355444, new Item.Properties()));
    public static final RegistryObject<Item> CREEPER_FISH_SPAWN_EGG = ITEMS.register("creeper_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CREEPER_FISH, -10092442, -3342337, new Item.Properties()));
    public static final RegistryObject<Item> PUNCTURE_FISH_SPAWN_EGG = ITEMS.register("puncture_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.PUNCTURE_FISH, -16750900, -1, new Item.Properties()));
    public static final RegistryObject<Item> SEA_TRAIL_INIT = block(ModBlocks.SEA_TRAIL_INIT);
    public static final RegistryObject<Item> SEA_TRAIL_GROWING = block(ModBlocks.SEA_TRAIL_GROWING);
    public static final RegistryObject<Item> SEA_TRAIL_GROWN = block(ModBlocks.SEA_TRAIL_GROWN);
    public static final RegistryObject<Item> SEA_TRAIL_MOR = ITEMS.register("sea_trail_mor", () -> new SeaTrailMorItem());
    public static final RegistryObject<Item> BOMB_TRAILER = block(ModBlocks.BOMB_TRAILER);
    public static final RegistryObject<Item> CANNED_WATER = ITEMS.register("canned_water", () -> new CannedWaterItem());
    public static final RegistryObject<Item> CANNED_LAVA = ITEMS.register("canned_lava", () -> new CannedLavaItem());
    public static final RegistryObject<Item> BONE_SHARD = ITEMS.register("bone_shard", () -> new BoneShardItem());
    public static final RegistryObject<Item> OCEAN_PHLOEM = ITEMS.register("ocean_phloem", () -> new OceanPhloemItem());
    public static final RegistryObject<Item> OCEAN_FIBRE = ITEMS.register("ocean_fibre", () -> new OceanFibreItem());
    public static final RegistryObject<Item> OCEAN_EYE = ITEMS.register("ocean_eye", () -> new OceanEyeItem());
    public static final RegistryObject<Item> OCEAN_CRYSTAL = ITEMS.register("ocean_crystal", () -> new OceanCrystalItem());
    public static final RegistryObject<Item> OCEAN_CUTIN = ITEMS.register("ocean_cutin", () -> new OceanCutinItem());
    public static final RegistryObject<Item> COOKED_FIBRE = ITEMS.register("cooked_fibre", () -> new CookedFibreItem());
    public static final RegistryObject<Item> BASELAYER_ABYSSAL_SPAWN_EGG = ITEMS.register("baselayer_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.BASELAYER_ABYSSAL, -16776961, -2056595, new Item.Properties()));
    public static final RegistryObject<Item> OCEAN_GLASS = block(ModBlocks.OCEAN_GLASS);
    public static final RegistryObject<Item> OCEAN_GLASSPANE = block(ModBlocks.OCEAN_GLASSPANE);
    public static final RegistryObject<Item> OCEAN_CHITIN = ITEMS.register("ocean_chitin", () -> new OceanChitinItem());
    public static final RegistryObject<Item> CHITIN_BLOCK = block(ModBlocks.CHITIN_BLOCK);
    public static final RegistryObject<Item> COOKED_MOR = ITEMS.register("cooked_mor", () -> new CookedMorItem());
    public static final RegistryObject<Item> SWORD_OCEAN_CRYSTAL = ITEMS.register("sword_ocean_crystal", () -> new SwordOceanCrystalItem());
    public static final RegistryObject<Item> CHITIN_ARMOR_HELMET = ITEMS.register("chitin_armor_helmet", () -> new ChitinArmorItem.Helmet());
    public static final RegistryObject<Item> CHITIN_ARMOR_CHESTPLATE = ITEMS.register("chitin_armor_chestplate", () -> new ChitinArmorItem.Chestplate());
    public static final RegistryObject<Item> CHITIN_ARMOR_LEGGINGS = ITEMS.register("chitin_armor_leggings", () -> new ChitinArmorItem.Leggings());
    public static final RegistryObject<Item> CHITIN_ARMOR_BOOTS = ITEMS.register("chitin_armor_boots", () -> new ChitinArmorItem.Boots());
    public static final RegistryObject<Item> CHITIN_PICKAXE = ITEMS.register("chitin_pickaxe", () -> new ChitinPickaxeItem());
    public static final RegistryObject<Item> CHITIN_AXE = ITEMS.register("chitin_axe", () -> new ChitinAxeItem());
    public static final RegistryObject<Item> CHITIN_SHOVEL = ITEMS.register("chitin_shovel", () -> new ChitinShovelItem());
    public static final RegistryObject<Item> CHITIN_HOE = ITEMS.register("chitin_hoe", () -> new ChitinHoeItem());
    public static final RegistryObject<Item> CHITIN_SWORD = ITEMS.register("chitin_sword", () -> new ChitinSwordItem());
    public static final RegistryObject<Item> PICKAXE_OCEAN_CRYSTAL = ITEMS.register("pickaxe_ocean_crystal", () -> new OceanthornPickaxeItem());
    public static final RegistryObject<Item> AXE_OCEAN_CRYSTAL = ITEMS.register("axe_ocean_crystal", () -> new OceanthornAxeItem());
    public static final RegistryObject<Item> SHOVEL_OCEAN_CRYSTAL = ITEMS.register("shovel_ocean_crystal", () -> new OceanthornShovelItem());
    public static final RegistryObject<Item> HOE_OCEAN_CRYSTAL = ITEMS.register("hoe_ocean_crystal", () -> new OceanthornHoeItem());
    public static final RegistryObject<Item> CUTIN_STICK = ITEMS.register("cutin_stick", () -> new CutinStickItem());
    public static final RegistryObject<Item> PREDATOR_ABYSSAL_SPAWN_EGG = ITEMS.register("predator_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.PREDATOR_ABYSSAL, -16777063, -2056595, new Item.Properties()));
    public static final RegistryObject<Item> BLOCK_KETTLE = block(ModBlocks.BLOCK_KETTLE);
    public static final RegistryObject<Item> INSTANT_NOODLE = ITEMS.register("instant_noodle", () -> new InstantNoodleItem());
    public static final RegistryObject<Item> CANNED_NOODLE = ITEMS.register("canned_noodle", () -> new CannedNoodleItem());
    public static final RegistryObject<Item> CANNED_BOILED_WATER = ITEMS.register("canned_boiled_water", () -> new CannedBoiledWaterItem());
    public static final RegistryObject<Item> OBISIDIAN_BALL = ITEMS.register("obisidian_ball", () -> new ObisidianBallItem());
    public static final RegistryObject<Item> CHITIN_KNIFE = ITEMS.register("chitin_knife", () -> new ChitinKnifeItem());
    public static final RegistryObject<Item> COMPLEX_CHITIN = ITEMS.register("complex_chitin", () -> new ComplexChitinItem());
    public static final RegistryObject<Item> COMPLEX_CHITIN_SWORD = ITEMS.register("complex_chitin_sword", () -> new ComplexChitinSwordItem());
    public static final RegistryObject<Item> OCEAN_TRIM_TEMPLATE = ITEMS.register("ocean_trim_template", () -> new OceanTrimTemplateItem());
    public static final RegistryObject<Item> COMPLEXCHITIN_ARMOR_HELMET = ITEMS.register("complexchitin_armor_helmet", () -> new ComplexchitinArmorItem.Helmet());
    public static final RegistryObject<Item> COMPLEXCHITIN_ARMOR_CHESTPLATE = ITEMS.register("complexchitin_armor_chestplate", () -> new ComplexchitinArmorItem.Chestplate());
    public static final RegistryObject<Item> COMPLEXCHITIN_ARMOR_LEGGINGS = ITEMS.register("complexchitin_armor_leggings", () -> new ComplexchitinArmorItem.Leggings());
    public static final RegistryObject<Item> COMPLEXCHITIN_ARMOR_BOOTS = ITEMS.register("complexchitin_armor_boots", () -> new ComplexchitinArmorItem.Boots());
    public static final RegistryObject<Item> COMPLEX_CHITIN_PICKAXE = ITEMS.register("complex_chitin_pickaxe", () -> new ComplexChitinPickaxeItem());
    public static final RegistryObject<Item> COMPLEX_CHITIN_AXE = ITEMS.register("complex_chitin_axe", () -> new ComplexChitinAxeItem());
    public static final RegistryObject<Item> COMPLEX_CHITIN_SHOVEL = ITEMS.register("complex_chitin_shovel", () -> new ComplexChitinShovelItem());
    public static final RegistryObject<Item> COMPLEX_CHITIN_HOE = ITEMS.register("complex_chitin_hoe", () -> new ComplexChitinHoeItem());
    public static final RegistryObject<Item> OCEAN_FARMLAND = block(ModBlocks.OCEAN_FARMLAND);
    public static final RegistryObject<Item> PHLOEM_BOW = ITEMS.register("phloem_bow", () -> new PhloemBowItem());
    public static final RegistryObject<Item> LEGENDARY_SPEAR = ITEMS.register("legendary_spear", () -> new LegendarySpearItem());
    public static final RegistryObject<Item> ALLAY_SCULPTURE = ITEMS.register("allay_sculpture", () -> new AlleySculptureItem());
    public static final RegistryObject<Item> ALLAY_BLOCK = block(ModBlocks.ALLAY_BLOCK);
    public static final RegistryObject<Item> BLOCK_BATBED = block(ModBlocks.BLOCK_BATBED);
    public static final RegistryObject<Item> BATBED_UPPER = block(ModBlocks.BATBED_UPPER);
    public static final RegistryObject<Item> OMNI_KEY = ITEMS.register("omni_key", () -> new OmniKeyItem());
    public static final RegistryObject<Item> SCORE = ITEMS.register("score", () -> new ScoreItem());
    public static final RegistryObject<Item> RESCISSION = ITEMS.register("rescission", () -> new RescissionItem());
    public static final RegistryObject<Item> LANGUAGE_KEY = ITEMS.register("language_key", () -> new LanguageKeyItem());
    public static final RegistryObject<Item> TRAIL_CAKE = block(ModBlocks.TRAIL_CAKE);
    public static final RegistryObject<Item> TRAIL_CAKE_PIECE = ITEMS.register("trail_cake_piece", () -> new TrailCakePieceItem());
    public static final RegistryObject<Item> CARAMEL_CAKE = block(ModBlocks.CARAMEL_CAKE);
    public static final RegistryObject<Item> CARAMEL_CAKE_PIECE = ITEMS.register("caramel_cake_piece", () -> new CaramelCakePieceItem());
    public static final RegistryObject<Item> CARAMEL_MOR = ITEMS.register("caramel_mor", () -> new CaramelMorItem());
    public static final RegistryObject<Item> GUIDE_ABYSSAL_SPAWN_EGG = ITEMS.register("guide_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.GUIDE_ABYSSAL, -13434778, -2056595, new Item.Properties()));
    public static final RegistryObject<Item> SPLASHER_ABYSSAL_SPAWN_EGG = ITEMS.register("splasher_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.SPLASHER_ABYSSAL, -16777012, -2056595, new Item.Properties()));
    public static final RegistryObject<Item> FAKE_EGG = ITEMS.register("fake_egg", () -> new FakeEggItem());
    public static final RegistryObject<Item> REAL_EGG = ITEMS.register("real_egg", () -> new RealEggItem());
    public static final RegistryObject<Item> FERMENTED_OCEAN_EYE = ITEMS.register("fermented_ocean_eye", () -> new FermentedOceanEyeItem());
    public static final RegistryObject<Item> OCEAN_MACHINE = ITEMS.register("ocean_machine", () -> new OceanMachineItem());
    public static final RegistryObject<Item> OCEAN_CRYSTAL_BLOCK = block(ModBlocks.OCEAN_CRYSTAL_BLOCK);
    public static final RegistryObject<Item> COMPLEX_CHITIN_BLOCK = block(ModBlocks.COMPLEX_CHITIN_BLOCK);
    public static final RegistryObject<Item> GUARDIAN_STARE = ITEMS.register("guardian_stare", () -> new GuardianStareItem());
    public static final RegistryObject<Item> HAND_SWORD = ITEMS.register("hand_sword", () -> new HandSwordItem());
    public static final RegistryObject<Item> TIDE_OBSERVATION = block(ModBlocks.TIDE_OBSERVATION);
    public static final RegistryObject<Item> SAMPLE_SUBSISTING = ITEMS.register("sample_subsisting", () -> new SampleSubsistingItem());
    public static final RegistryObject<Item> SAMPLE_GROW = ITEMS.register("sample_grow", () -> new SampleGrowItem());
    public static final RegistryObject<Item> SAMPLE_BREED = ITEMS.register("sample_breed", () -> new SampleBreedItem());
    public static final RegistryObject<Item> SAMPLE_MIGRATION = ITEMS.register("sample_migration", () -> new SampleMigrationItem());
    public static final RegistryObject<Item> ANCHOR_LOWER = block(ModBlocks.ANCHOR_LOWER);
    public static final RegistryObject<Item> ANCHOR_MEDIUM = block(ModBlocks.ANCHOR_MEDIUM);
    public static final RegistryObject<Item> ANCHOR_UPPER = block(ModBlocks.ANCHOR_UPPER);
    public static final RegistryObject<Item> UMBRELLA_ABYSSAL_SPAWN_EGG = ITEMS.register("umbrella_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.UMBRELLA_ABYSSAL, -10066177, -2056595, new Item.Properties()));
    public static final RegistryObject<Item> TRAILED_WOODEN_SWORD = ITEMS.register("trailed_wooden_sword", () -> new TrailedWoodenSwordItem());
    public static final RegistryObject<Item> TRAILED_STONE_SWORD = ITEMS.register("trailed_stone_sword", () -> new TrailedStoneSwordItem());
    public static final RegistryObject<Item> TRAILED_IRON_SWORD = ITEMS.register("trailed_iron_sword", () -> new TrailedIronSwordItem());
    public static final RegistryObject<Item> TRAILED_DIAMOND_SWORD = ITEMS.register("trailed_diamond_sword", () -> new TrailedDiamondSwordItem());
    public static final RegistryObject<Item> TRAILED_NETHERITE_SWORD = ITEMS.register("trailed_netherite_sword", () -> new TrailedNetheriteSwordItem());
    public static final RegistryObject<Item> TRAILED_GOLDEN_SWORD = ITEMS.register("trailed_golden_sword", () -> new TrailedGoldenSwordItem());
    public static final RegistryObject<Item> TRAIL_CREAM = ITEMS.register("trail_cream", () -> new TrailCreamItem());
    public static final RegistryObject<Item> CRACKER_ABYSSAL_SPAWN_EGG = ITEMS.register("cracker_abyssal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CRACKER_ABYSSAL, -16777012, -2056595, new Item.Properties()));
    public static final RegistryObject<Item> DISPATCH_STICK = ITEMS.register("dispatch_stick", () -> new DispatchStickItem());
    public static final RegistryObject<Item> COLLECTOR_PROKARYOTE_SPAWN_EGG = ITEMS.register("collector_prokaryote_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.COLLECTOR_PROKARYOTE, -16776961, -16316408, new Item.Properties()));
    public static final RegistryObject<Item> BROKEN_OCEAN_CELL = ITEMS.register("broken_ocean_cell", () -> new BrokenOceanCellItem());
    public static final RegistryObject<Item> BROKEN_CELL_CLUSTER = ITEMS.register("broken_cell_cluster", () -> new BrokenCellClusterItem());
    public static final RegistryObject<Item> OCEAN_CELL = ITEMS.register("ocean_cell", () -> new OceanCellItem());
    public static final RegistryObject<Item> CELL_CLUSTER = ITEMS.register("cell_cluster", () -> new CellClusterItem());
    public static final RegistryObject<Item> COOKED_BROKEN_CELL_CLUSTER = ITEMS.register("cooked_broken_cell_cluster", () -> new CookedBrokenCellClusterItem());
    public static final RegistryObject<Item> COOKED_CELL_CLUSTER = ITEMS.register("cooked_cell_cluster", () -> new CookedCellClusterItem());
    public static final RegistryObject<Item> TRANSFORM_CELL = ITEMS.register("transform_cell", () -> new TransformCellItem());
    public static final RegistryObject<Item> BONE_FISH_SPAWN_EGG = ITEMS.register("bone_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.BONE_FISH, -10066177, -1, new Item.Properties()));
    public static final RegistryObject<Item> BLOCK_RECORDER = block(ModBlocks.BLOCK_RECORDER);
    public static final RegistryObject<Item> CHISELER_FISH_SPAWN_EGG = ITEMS.register("chiseler_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.CHISELER_FISH, -10053121, -1, new Item.Properties()));
    public static final RegistryObject<Item> PREGNANT_FISH_SPAWN_EGG = ITEMS.register("pregnant_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.PREGNANT_FISH, -10066177, -1, new Item.Properties()));
    public static final RegistryObject<Item> FAKE_OFFSPRING_SPAWN_EGG = ITEMS.register("fake_offspring_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FAKE_OFFSPRING, -856596, -6711916, new Item.Properties()));
    public static final RegistryObject<Item> FLEE_FISH_SPAWN_EGG = ITEMS.register("flee_fish_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.FLEE_FISH, -16764007, -1, new Item.Properties()));
    public static final RegistryObject<Item> ROUTE_SHAPER_SPAWN_EGG = ITEMS.register("route_shaper_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.ROUTE_SHAPER, -16764007, -10040065, new Item.Properties()));
    public static final RegistryObject<Item> ROUTE_FRACTAL_SPAWN_EGG = ITEMS.register("route_fractal_spawn_egg", () -> new ForgeSpawnEggItem(CaerulaArborModEntities.ROUTE_FRACTAL, -16777165, -16764109, new Item.Properties()));
    public static final RegistryObject<Item> SEA_TRAIL_SOLID = block(ModBlocks.SEA_TRAIL_SOLID);
    public static final RegistryObject<Item> TRAIL_BRICK = block(ModBlocks.TRAIL_BRICK);
    public static final RegistryObject<Item> TRAIL_SLAB = block(ModBlocks.TRAIL_SLAB);
    public static final RegistryObject<Item> TRAIL_STAIR = block(ModBlocks.TRAIL_STAIR);
    public static final RegistryObject<Item> TRAIL_BUTTON = block(ModBlocks.TRAIL_BUTTON);
    public static final RegistryObject<Item> TRAIL_PRESSURE_PLATE = block(ModBlocks.TRAIL_PRESSURE_PLATE);
    public static final RegistryObject<Item> TRAIL_TILE = block(ModBlocks.TRAIL_TILE);
    public static final RegistryObject<Item> CAERULA_HEART = ITEMS.register("caerula_heart", () -> new CaerulaHeartItem());
    public static final RegistryObject<Item> COIN_OF_TRADE = ITEMS.register("coin_of_trade", () -> new CoinOfTradeItem());
    public static final RegistryObject<Item> OCEAN_PEDUNCLE = ITEMS.register("ocean_peduncle", () -> new OceanPeduncleItem());
    public static final RegistryObject<Item> ELITE_PEDUNCLE = ITEMS.register("elite_peduncle", () -> new ElitePeduncleItem());
    public static final RegistryObject<Item> COOKED_PEDUNCLE = ITEMS.register("cooked_peduncle", () -> new CookedPeduncleItem());
    public static final RegistryObject<Item> OCEAN_ARROW = ITEMS.register("ocean_arrow", () -> new OceanArrowItem());

    /**
     * Relics
     */
    public static final DeferredRegister<Item> RELICS = DeferredRegister.create(ForgeRegistries.ITEMS, CaerulaArborMod.MODID);

    public static final RegistryObject<Item> HOT_WATER_KETTLE = RELICS.register("hot_water_kettle", HotWaterKettleItem::new);
    public static final RegistryObject<Item> VAMPIRES_BED = RELICS.register("vampires_bed", VampiresBedItem::new);
    public static final RegistryObject<Item> FEATURED_CANNED_MEAT = RELICS.register("featured_canned_meat", FeaturedCannedMeatItem::new);
    public static final RegistryObject<Item> PURE_GOLD_EXPEDITION = RELICS.register("pure_gold_expedition", PureGoldExpeditionItem::new);
    public static final RegistryObject<Item> PITTS_ASSORTED_FRUITS = RELICS.register("pitts_assorted_fruits", PittsAssortedFruitsItem::new);
    public static final RegistryObject<Item> SCREAMING_CHERRY = RELICS.register("screaming_cherry", ScreamingCherryItem::new);
    public static final RegistryObject<Item> PROOF_OF_LONGEVITY = RELICS.register("proof_of_longevity", ProofOfLongevityItem::new);
    public static final RegistryObject<Item> WEIRD_FLUTE = RELICS.register("weird_flute", WeirdFluteItem::new);
    public static final RegistryObject<Item> DURIN_OVERGROUND_ODYSSEY = RELICS.register("durin_overground_odyssey", DurinOvergroundOdysseyItem::new);

    public static final RegistryObject<Item> SURVIVOR_CONTRACT = RELICS.register("survivor_contract", SurvivorContractItem::new);

    /**
     * Spawn Eggs
     */
    public static final DeferredRegister<Item> SPAWN_EGGS = DeferredRegister.create(ForgeRegistries.ITEMS, CaerulaArborMod.MODID);

    private static RegistryObject<Item> block(RegistryObject<Block> block) {
        return ITEMS.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
    }

    public static void register(IEventBus bus) {
        ITEMS.register(bus);
        RELICS.register(bus);
        SPAWN_EGGS.register(bus);
    }

    @SubscribeEvent
    public static void clientLoad(FMLClientSetupEvent event) {
        event.enqueueWork(() -> {
            ItemProperties.register(MUSIC_BOX_FIXED.get(), new ResourceLocation("caerula_arbor:music_box_fixed_playing"),
                    (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetMusicboxPlayerProcedure.execute(entity, itemStackToRender));
        });
    }
}
